FROM python:3

{{install_cob}}
COPY . /app
WORKDIR /app
RUN cob -vvv bootstrap
RUN /app/.cob/env/bin/pip3 install gunicorn
{{user_steps}}
EXPOSE 80
CMD ["/app/.cob/env/bin/gunicorn", "-b", "0.0.0.0:80", "cob.utils.wsgi:app"]
